version: '3.8'  # or you can remove this line based on the warning message

services:
  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile  # Specify the correct path if it's in the `api` folder
    ports:
      - "5000:80"
    depends_on:
      - sql_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
